### ISSUE TITLE
install.sh脚本在root下无法运行

### ISSUE THREAD

**Issue by rhettor** [DesnLee/Sub-Store-Manager-Cli#1]
系统未安装sudo，只存在root用户，使用root用户无法继续执行

**Comment by DesnLee** [comment]
> 系统未安装sudo，只存在root用户，使用root用户无法继续执行

报错看看呢

**Comment by rhettor** [comment]
> > 系统未安装sudo，只存在root用户，使用root用户无法继续执行
> 
> 报错看看呢

判断下用户类型，如果是root就不通过sudo执行

**Comment by DesnLee** [comment]
sudo 删掉了，你再试试看吧

**Comment by rhettor** [comment]
> sudo 删掉了，你再试试看吧

 嗯，可以了，普通用户可能就需要过外部sudo来运行
