### ISSUE TITLE
缺少鉴权，很不安全

### ISSUE THREAD

**Issue by zkl2333** [DesnLee/Sub-Store-Manager-Cli#11]
如题，阅读文档后没发现有类似密码或者密钥的配置。
后端暴露的数据都是非常敏感的：如节点配置 和 github token。
建议在文档补充安全方面的细节。

**Comment by DesnLee** [comment]
> 如题，阅读文档后没发现有类似密码或者密钥的配置。
> 
> 后端暴露的数据都是非常敏感的：如节点配置 和 github token。
> 
> 建议在文档补充安全方面的细节。

如果需要把服务端暴露在公网的话，目前建议自行使用反向代理工具如 Nginx 将服务代理到一个 path 下而非 / 下，path 可以使用一个 64 位甚至 128 位的随机字符串来防止未经授权的访问
