### ISSUE TITLE
请问，用 ssm new 安装的 backend 如何设置 SUB_STORE_FRONTEND_BACKEND_PATH ？

### ISSUE THREAD

**Issue by shao222** [DesnLee/Sub-Store-Manager-Cli#13]
如题，请问 ssm new 安装的 sub-store docker ，
如何设置 `SUB_STORE_FRONTEND_BACKEND_PATH` 环境参数？

谢谢🙏

**Comment by DesnLee** [comment]
目前只能在nginx之类的反向代理服务器上配置 path

**Comment by shao222** [comment]
> 目前只能在nginx之类的反向代理服务器上配置 path

感谢，确实可以这么做。

Lucky for OpenWrt 已成功反代内网API 。
