### ISSUE TITLE
Error:  The port is unavailable. 

### ISSUE THREAD

**Issue by qingweiSun** [DesnLee/Sub-Store-Manager-Cli#2]
[root@VM-4-3-centos ~]# ssm new substore
No version specified, using the latest version
Error:  The port is unavailable.

**Comment by DesnLee** [comment]
指定容器名称应该使用 -n 再接名称。
报错原因是默认端口已经被占用，使用 -p 指定一个未被占用的端口即可

**Comment by qingweiSun** [comment]
谢谢
