### ISSUE TITLE
Cannot run external script.

### ISSUE THREAD

**Issue by Energetic3906** [DesnLee/Sub-Store-Manager-Cli#3]
When running the script, there is a cache error.

![image](https://github.com/sub-store-org/Sub-Store-Manager-Cli/assets/101653181/129ec196-c5dd-48f4-8bce-56efb8cf4fe7)

**Comment by DesnLee** [comment]
These are the logs of the Sub-Store Backend. Please create a new issue in [Sub-Store New Issue](https://github.com/sub-store-org/Sub-Store/issues/new).
