### ISSUE TITLE
能否支持修改后端端口重定向地址和持久化前端数据

### ISSUE THREAD

**Issue by somnifex** [DesnLee/Sub-Store-Manager-Cli#4]
后端端口默认重定向到了https://sub-store.vercel.app/subs，能否修改为自己的前端地址
能否在前端增加持久化存储，存储前端容器连接的后端，方便跨设备跨浏览器使用

**Comment by DesnLee** [comment]
- 默认重定向目前暂不支持

- 前端容器连接的后端可以通过 url 参数 `http(s)://前端地址?api=后端地址` 进行默认配置，所以你可以直接保存带着 url 参数的地址书签来使用

**Comment by somnifex** [comment]
> * 默认重定向目前暂不支持
> * 前端容器连接的后端可以通过 url 参数 `http(s)://前端地址?api=后端地址` 进行默认配置，所以你可以直接保存带着 url 参数的地址书签来使用

明白，感谢回复
