### ISSUE TITLE
Allow users to specify the Network of the container

### ISSUE THREAD

**Issue by feewg** [DesnLee/Sub-Store-Manager-Cli#5]
# 建议
Docker容器内部设定好以后是可以互相访问的
在使用Nginx Proxy Manager这类docker时可以直接通过容器名称和端口来反代，而不用将端口映射到主机
这样做可以增加安全性，以及减少端口使用

**Comment by DesnLee** [comment]
你指的是docker的network功能吗？

**Comment by feewg** [comment]
> 你指的是docker的network功能吗？

是的

**Comment by DesnLee** [comment]
https://github.com/sub-store-org/Sub-Store-Manager-Cli/commit/b40396c3dce18962137b5cec23c504a0076e7767

已经添加了 --network flag 用来指定 docker 容器的网络，如果该名称的网络不存在则会创建，存在则直接加入。

请等待下一个 release

**Comment by DesnLee** [comment]
已经发布 [release](https://github.com/sub-store-org/Sub-Store-Manager-Cli/releases/tag/0.0.10)，可以更新后尝试是否如期运行
